image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

    # Env file highlight
    - irongeek.vscode-env

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

tasks:
  - init: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod pull
  - command: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod up
