image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    # Docker helper extension
    - ms-azuretools.vscode-docker

    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

    # Env file highlight
    - mikestead.dotenv

    # Github Theme
    - github.github-vscode-theme

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

# Define Ports and how they should be handled
# Documentation: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 8000
    onOpen: open-browser
    visibility: public
    name: cyb webserver
    description: shows cyb application on the browser

tasks:
  - init: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod pull
  - command: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod up
