tasks:
  - init: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod build && ./cyb-app/run-docker.sh gitpod pull
  - command: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod up
