image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - felixfbecker.php-debug

tasks:
  - init: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod pull
  - command: chmod +x ./cyb-app/run-docker.sh && ./cyb-app/run-docker.sh gitpod up
