version: "3"

networks:
  cyb-network:
    name: "cyb-net"

services:
  cyb:
    image: ghcr.io/pondersource/cyb:latest
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        CYBGID: 33333
        CYBUID: 33333
        # change this if ypu want to build cyb image from a specific
        # repository and branch.
        BUILD_REPO: "https://github:com/pondersource/CYB/archive/refs/heads"
        BUILD_BRANCH: "main"
    container_name: cyb
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - target: 8000
        published: 8000
        mode: host
    env_file:
      - docker.gitpod.env
    environment:
      CYB_APP_MODE: "development"
      APP_CONTAINER_ROLE: "app"
      APP_WEBSERVER_TYPE: "artisan"
      XDEBUG_MODE: "develop,debug,coverage"
      XDEBUG_CONFIG: "idekey=ECLIPSE client_host=host.docker.internal"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}:/var/www/html"
    healthcheck:
      test: [ "CMD", "node" , "/cyb-src/healthcheck.js" ]
      timeout: 2s
      retries: 100
    depends_on:
      cyb-mariadb:
        condition: service_healthy
      cyb-redis:
        condition: service_healthy

  cyb-horizon:
    image: ghcr.io/pondersource/cyb:latest
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        CYBGID: 1000
        CYBUID: 1000
        # change this if ypu want to build cyb image from a specific
        # repository and branch.
        BUILD_REPO: "https://github:com/pondersource/CYB/archive/refs/heads"
        BUILD_BRANCH: "main"
    container_name: cyb-horizon
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    env_file:
      - docker.gitpod.env
    environment:
      APP_CONTAINER_ROLE: "horizon"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}:/var/www/html:ro"
    depends_on:
      cyb:
        condition: service_healthy

  cyb-scheduler:
    image: ghcr.io/pondersource/cyb:latest
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        CYBGID: 1000
        CYBUID: 1000
        # change this if ypu want to build cyb image from a specific
        # repository and branch.
        BUILD_REPO: "https://github:com/pondersource/CYB/archive/refs/heads"
        BUILD_BRANCH: "main"
    container_name: cyb-scheduler
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    env_file:
      - docker.gitpod.env
    environment:
      APP_CONTAINER_ROLE: "scheduler"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}:/var/www/html:ro"
    depends_on:
      cyb:
        condition: service_healthy

  cyb-mariadb:
    image: "mariadb:10.9.2-jammy"
    container_name: cyb-mariadb
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    command: mysqld --max-allowed-packet=64MB
    env_file:
      - docker.gitpod.env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: [
        "CMD",
        "mysqladmin" , "ping",
        "--host", "localhost",
        "--port", "3306",
        "--user=cyb",
        "--password=simpleYetNotSecure"
      ]
      timeout: 2s
      retries: 100

  cyb-redis:
    image: "redis:7.0.4-bullseye"
    container_name: cyb-redis
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 2s
      retries: 100
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
