version: "3"

networks:
  cyb-network:


services:
  cyb:
    image: "lara-test"
    build:
      context: .
    container_name: cyb
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    ports:
      - target: 8000
        published: 8000
        mode: host
    entrypoint: sh -c "cd /app && php artisan migrate --force && php artisan optimize && php artisan serv --host=0.0.0.0"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:1IKnsyc2Om+mWPqSKr44xdSTkzFQNS3xR9IRsX0ovG8=
      APP_DEBUG: true
      # Database Configuration.
      DB_CONNECTION: mysql
      DB_HOST: cyb-mariadb
      DB_PORT: 3306
      DB_DATABASE: cyb_db
      DB_USERNAME: cyb
      DB_PASSWORD: "simpleYetNotSecure"
      # Redis Configuration.
      REDIS_HOST: cyb-redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      REDIS_CLIENT: predis
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      cyb-mariadb:
        condition: service_healthy
      cyb-redis:
        condition: service_healthy

  cyb-mariadb:
    image: "mariadb:10.9.2-jammy"
    container_name: cyb-mariadb
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    command: mysqld --max-allowed-packet=64MB
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "cyb_db"
      MYSQL_USER: "cyb"
      MYSQL_PASSWORD: "simpleYetNotSecure"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 100

  cyb-redis:
    image: "redis:7.0.4-bullseye"
    container_name: cyb-redis
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      - cyb-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 2s
      retries: 100
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
